import Testing
@testable import AdventOfCode

struct Y2025Day07Tests {
  let testData = """
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  """

  @Test func testPart1() async throws {
    let challenge = Y2025Day07(data: testData)
    #expect(challenge.part1() == 21)
  }

  @Test func testPart2() async throws {
    let challenge = Y2025Day07(data: testData)
    #expect(challenge.part2() == 40)
  }
}
